#' CIBERSORTx Results for P. Falciparum Heat Shock Bulks to MCA data
#' 
#' These are CIBERSORTx results for mapping Zhang et al.'s P. falciparum heat shock
#' RNA-seq data to Howick et al.'s Malaria Cell Atlas P. Falciaprum scRNA-seq
#'
#'
#' Exact steps for generating this object are given in
#' [our article](articles/DE_with_blase).
#'
#' @format
#' The object contains a CIBERSORTx results table. This includes proportion
#' estimations for pseudobins 1-8 (X1-X8), and quality scores (P.value, Correlation, RMSE)
#'
#' @source DE with BLASE vignette & CIBERSORTx
#' @usage data(cibersort_results, package='blase')
#' @concept blase-data
"cibersort_results"

#' BLASE Malaria Cell Atlas Plasmodium Berghei Test Dataset
#'
#' This is a [SingleCellExperiment] object which contains 4890 cells and 4763 genes.
#' It is used to test BLASE with a real dataset of Plasmodium Berghei, in
#' this case generated by [Howick et al. 2019](https://doi.org/10.1126/science.aaw2619).
#'
#' Exact steps for generating this object are given in
#' [our article](articles/generate-MCA-pb-object).
#'
#' @format
#' The object contains raw, normalized and log normalized counts, cluster names,
#' and PCA and UMAP coordinates, as well as pre-calculated slingshot trajectory
#' and tradeSeq analysis.
#'
#' @source <https://doi.org/10.1126/science.aaw2619>
#' @usage data(processed_MCA_PB_SCE, package='blase')
#' @concept blase-data
"processed_MCA_PB_SCE"

#' BLASE Malaria Cell Atlas Plasmodium Falciparum Test Dataset
#'
#' This is a [SingleCellExperiment] object which contains 6000 cells and 710 genes.
#' It is used to test BLASE with a real dataset of Plasmodium Falciparum, in
#' this case generated by [Dogga et al. 2023](https://www.science.org/doi/10.1126/science.adj4088).
#'
#' Exact steps for generating this object are given in
#' [our article](articles/generate-MCA-pf-object).
#'
#' @format
#' The object contains raw, normalized and log normalized counts, cluster names,
#' and PCA and UMAP coordinates, as well as pre-calculated slingshot trajectory
#' and tradeSeq analysis.
#'
#' @source <https://doi.org/10.1126/science.aaw2619>
#' @usage data(processed_MCA_PF_SCE, package='blase')
#' @concept blase-data
"processed_MCA_PF_SCE"

#' BLASE Simulation Test Dataset
#'
#' This is a SingleCellExperiment object which contains 2000 cells and 455 genes.
#' It is used to test BLASE in a dataset where the ground truth is known. It was
#' generated with the dyngen library.
#'
#' Exact steps for generating this object are given in
#' [our article](articles/generate-simulated-data-object).
#'
#' @format
#' The object contains raw, normalized and log normalized counts, cluster names,
#' and PCA and UMAP coordinates.
#'
#' @source BLASE
#' @usage data(processed_simulated_data_SCE, package='blase')
#' @concept blase-data
"processed_simulated_data_SCE"

#' Zhang et al. 2021 Plasmodium falciparum heat shock bulk RNA-seq FPKM data.
#' 
#' To re-generate, use the <articles/generate-zhang-et-al-2021-bulk-FPKM-object>
#'
#' @format
#' The object contains FPKM normalised bulk RNA-seq counts. Each row is a gene, 
#' and each column is a sample. The column name format is: "${line}_${heat_shock_temp}_${replciate_number}"
#'
#' @source <https://doi.org/10.1038/s41467-021-24814-1>
#' @usage data(zhang_2021_heat_shock_bulk, package='blase')
#' @concept blase-data
"zhang_2021_heat_shock_bulk"
