#' BLASE Malaria Cell Atlas Plasmodium Berghei Test Dataset
#'
#' This is a [SingleCellExperiment] object which contains 4890 cells and 4763 genes.
#' It is used to test BLASE with a real dataset of Plasmodium Berghei, in
#' this case generated by [Howick et al. 2019](https://doi.org/10.1126/science.aaw2619).
#'
#' Exact steps for generating this object are given in
#' [our article](articles/generate-MCA-pb-object).
#'
#' @format
#' The object contains raw, normalized and log normalized counts, cluster names,
#' and PCA and UMAP coordinates, as well as pre-calculated slingshot trajectory
#' and tradeSeq analysis.
#'
#' @source <https://doi.org/10.1126/science.aaw2619>
#' @usage data(processed_MCA_PB_SCE, package='blase')
#' @concept blase-data
"processed_MCA_PB_SCE"

#' BLASE Malaria Cell Atlas Plasmodium Falciparum Test Dataset
#'
#' This is a [SingleCellExperiment] object which contains 6000 cells and 710 genes.
#' It is used to test BLASE with a real dataset of Plasmodium Falciparum, in
#' this case generated by [Howick et al. 2019](https://doi.org/10.1126/science.aaw2619).
#'
#' Exact steps for generating this object are given in
#' [our article](articles/generate-MCA-pf-object).
#'
#' @format
#' The object contains raw, normalized and log normalized counts, cluster names,
#' and PCA and UMAP coordinates, as well as pre-calculated slingshot trajectory
#' and tradeSeq analysis.
#'
#' @source <https://doi.org/10.1126/science.aaw2619>
#' @usage data(processed_MCA_PF_SCE, package='blase')
#' @concept blase-data
"processed_MCA_PF_SCE"

#' BLASE Simulation Test Dataset
#'
#' This is a SingleCellExperiment object which contains 2000 cells and 455 genes.
#' It is used to test BLASE in a dataset where the ground truth is known. It was
#' generated with the dyngen library.
#'
#' Exact steps for generating this object are given in
#' [our article](articles/generate-simulated-data-object).
#'
#' @format
#' The object contains raw, normalized and log normalized counts, cluster names,
#' and PCA and UMAP coordinates.
#'
#' @source BLASE
#' @usage data(processed_simulated_data_SCE, package='blase')
#' @concept blase-data
"processed_simulated_data_SCE"
